project_id = "plfaixcjzrhpaxfhfstd"

[functions.delete-teacher-account]
verify_jwt = false

[functions.create-teacher-account]
verify_jwt = false

[functions.setup-teacher-accounts]
verify_jwt = false

[functions.generate-variations]
verify_jwt = false

[functions.parse-cb-question]
verify_jwt = false

[functions.parse-english-question]
verify_jwt = false

[functions.sync-external-questions]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.verify-password-reset]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
