project_id = "plfaixcjzrhpaxfhfstd"

[functions.delete-teacher-account]
verify_jwt = false

[functions.create-teacher-account]
verify_jwt = false

[functions.setup-teacher-accounts]
verify_jwt = false

[functions.generate-variations]
verify_jwt = false

[functions.parse-cb-question]
verify_jwt = false

[functions.parse-english-question]
verify_jwt = false

[functions.sync-external-questions]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.notify-attendance-change]
verify_jwt = false

[functions.send-welcome-sms]
verify_jwt = false

[functions.send-fee-paid-sms]
verify_jwt = false

[functions.send-batch-start-reminder]
verify_jwt = false

[functions.send-broadcast-sms]
verify_jwt = false
