-- Add device registration and blocking columns to student_accounts
ALTER TABLE public.student_accounts
ADD COLUMN IF NOT EXISTS registered_device_id text,
ADD COLUMN IF NOT EXISTS device_registered_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS is_blocked boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS blocked_reason text,
ADD COLUMN IF NOT EXISTS blocked_at timestamp with time zone;

-- Create vocabulary_words table
CREATE TABLE public.vocabulary_words (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  word_number integer NOT NULL UNIQUE,
  english text NOT NULL,
  mongolian text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS on vocabulary_words
ALTER TABLE public.vocabulary_words ENABLE ROW LEVEL SECURITY;

-- Only allow reading vocabulary words (no insert/update/delete for students)
CREATE POLICY "Anyone can view active vocabulary words"
ON public.vocabulary_words
FOR SELECT
USING (is_active = true);

-- Admins can manage vocabulary
CREATE POLICY "Admins can manage vocabulary words"
ON public.vocabulary_words
FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Create security_alerts table
CREATE TABLE public.security_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  student_account_id uuid NOT NULL REFERENCES public.student_accounts(id) ON DELETE CASCADE,
  alert_type text NOT NULL,
  severity text NOT NULL DEFAULT 'medium',
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed boolean NOT NULL DEFAULT false,
  reviewed_by text,
  reviewed_at timestamp with time zone
);

-- Enable RLS on security_alerts
ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;

-- Public can insert security alerts (for logging from frontend)
CREATE POLICY "Public can insert security alerts"
ON public.security_alerts
FOR INSERT
WITH CHECK (true);

-- Admins can manage security alerts
CREATE POLICY "Admins can manage security alerts"
ON public.security_alerts
FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Insert vocabulary words
INSERT INTO public.vocabulary_words (word_number, english, mongolian) VALUES
(1, 'Abandon', 'Орхих'),
(2, 'Abolish', 'Устгах'),
(3, 'Abrupt', 'Гэнэтийн'),
(4, 'Abundant', 'Элбэг'),
(5, 'Accelerate', 'Хурдасгах'),
(6, 'Accommodate', 'Байрлуулах'),
(7, 'Accumulate', 'Хуримтлуулах'),
(8, 'Accurate', 'Нарийвчлалтай'),
(9, 'Acknowledge', 'Хүлээн зөвшөөрөх'),
(10, 'Acquire', 'Олж авах'),
(11, 'Adapt', 'Дасан зохицох'),
(12, 'Adequate', 'Хангалттай'),
(13, 'Adjacent', 'Зэргэлдээ'),
(14, 'Advocate', 'Өмгөөлөх'),
(15, 'Affirm', 'Баталгаажуулах'),
(16, 'Aggregate', 'Нэгтгэх'),
(17, 'Allocate', 'Хуваарилах'),
(18, 'Alter', 'Өөрчлөх'),
(19, 'Ambiguous', 'Хоёрдмол'),
(20, 'Amend', 'Засварлах'),
(21, 'Analyze', 'Шинжлэх'),
(22, 'Anticipate', 'Таамаглах'),
(23, 'Apparent', 'Илэрхий'),
(24, 'Appreciate', 'Үнэлэх'),
(25, 'Approach', 'Хандлага'),
(26, 'Appropriate', 'Зохистой'),
(27, 'Arbitrary', 'Дурын'),
(28, 'Aspect', 'Тал'),
(29, 'Assert', 'Батлах'),
(30, 'Assess', 'Үнэлэх'),
(31, 'Assign', 'Томилох'),
(32, 'Assist', 'Туслах'),
(33, 'Assume', 'Таамаглах'),
(34, 'Assure', 'Баталгаажуулах'),
(35, 'Attain', 'Хүрэх'),
(36, 'Attribute', 'Шинж чанар'),
(37, 'Authorize', 'Зөвшөөрөх'),
(38, 'Aware', 'Мэдлэгтэй'),
(39, 'Behalf', 'Өмнөөс'),
(40, 'Benefit', 'Ашиг тус'),
(41, 'Bias', 'Хэвийн бус'),
(42, 'Brief', 'Товч'),
(43, 'Capable', 'Чадвартай'),
(44, 'Capacity', 'Багтаамж'),
(45, 'Category', 'Ангилал'),
(46, 'Cease', 'Зогсоох'),
(47, 'Challenge', 'Сорилт'),
(48, 'Channel', 'Суваг'),
(49, 'Circumstance', 'Нөхцөл байдал'),
(50, 'Clarify', 'Тодруулах'),
(51, 'Classic', 'Сонгодог'),
(52, 'Clause', 'Заалт'),
(53, 'Coincide', 'Давхцах'),
(54, 'Collapse', 'Нурах'),
(55, 'Colleague', 'Хамт олон'),
(56, 'Commence', 'Эхлэх'),
(57, 'Comment', 'Тайлбар'),
(58, 'Commission', 'Комисс'),
(59, 'Commit', 'Амлах'),
(60, 'Commodity', 'Бараа'),
(61, 'Communicate', 'Харилцах'),
(62, 'Community', 'Нийгэмлэг'),
(63, 'Compatible', 'Нийцтэй'),
(64, 'Compensate', 'Нөхөн төлөх'),
(65, 'Compile', 'Эмхэтгэх'),
(66, 'Complement', 'Нэмэлт'),
(67, 'Complex', 'Нарийн төвөгтэй'),
(68, 'Component', 'Бүрэлдэхүүн хэсэг'),
(69, 'Comprehensive', 'Иж бүрэн'),
(70, 'Comprise', 'Бүрдүүлэх'),
(71, 'Compute', 'Тооцоолох'),
(72, 'Conceive', 'Ойлгох'),
(73, 'Concentrate', 'Төвлөрөх'),
(74, 'Concept', 'Ойлголт'),
(75, 'Conclude', 'Дүгнэх'),
(76, 'Concurrent', 'Зэрэгцээ'),
(77, 'Conduct', 'Явуулах'),
(78, 'Confer', 'Зөвлөлдөх'),
(79, 'Confine', 'Хязгаарлах'),
(80, 'Confirm', 'Батлах'),
(81, 'Conflict', 'Зөрчилдөөн'),
(82, 'Conform', 'Дагах'),
(83, 'Consent', 'Зөвшөөрөл'),
(84, 'Consequent', 'Үр дүн'),
(85, 'Considerable', 'Ихээхэн'),
(86, 'Consist', 'Бүрдэх'),
(87, 'Constant', 'Тогтмол'),
(88, 'Constitute', 'Бүрдүүлэх'),
(89, 'Constrain', 'Хязгаарлах'),
(90, 'Construct', 'Барих'),
(91, 'Consult', 'Зөвлөлдөх'),
(92, 'Consume', 'Хэрэглэх'),
(93, 'Contact', 'Холбоо барих'),
(94, 'Contemporary', 'Орчин үеийн'),
(95, 'Context', 'Нөхцөл байдал'),
(96, 'Contract', 'Гэрээ'),
(97, 'Contradict', 'Зөрчих'),
(98, 'Contrary', 'Эсрэг'),
(99, 'Contrast', 'Ялгаа'),
(100, 'Contribute', 'Хувь нэмэр оруулах'),
(101, 'Controversy', 'Маргаан'),
(102, 'Convene', 'Хуралдуулах'),
(103, 'Converse', 'Эсрэг'),
(104, 'Convert', 'Хөрвүүлэх'),
(105, 'Convince', 'Итгүүлэх'),
(106, 'Cooperate', 'Хамтран ажиллах'),
(107, 'Coordinate', 'Зохицуулах'),
(108, 'Core', 'Гол'),
(109, 'Corporate', 'Корпорацийн'),
(110, 'Correspond', 'Тохирох'),
(111, 'Create', 'Бүтээх'),
(112, 'Criterion', 'Шалгуур'),
(113, 'Crucial', 'Чухал'),
(114, 'Culture', 'Соёл'),
(115, 'Decade', 'Арван жил'),
(116, 'Decline', 'Буурах'),
(117, 'Deduce', 'Дүгнэх'),
(118, 'Define', 'Тодорхойлох'),
(119, 'Definite', 'Тодорхой'),
(120, 'Demonstrate', 'Харуулах'),
(121, 'Denote', 'Илэрхийлэх'),
(122, 'Deny', 'Үгүйсгэх'),
(123, 'Depress', 'Дарамтлах'),
(124, 'Derive', 'Гаргах'),
(125, 'Design', 'Дизайн'),
(126, 'Despite', 'Хэдий ч'),
(127, 'Detect', 'Илрүүлэх'),
(128, 'Deviate', 'Хазайх'),
(129, 'Device', 'Төхөөрөмж'),
(130, 'Devote', 'Зориулах'),
(131, 'Differentiate', 'Ялгах'),
(132, 'Dimension', 'Хэмжээс'),
(133, 'Diminish', 'Багасгах'),
(134, 'Discrete', 'Тусдаа'),
(135, 'Discriminate', 'Ялгаварлах'),
(136, 'Displace', 'Шилжүүлэх'),
(137, 'Display', 'Харуулах'),
(138, 'Dispose', 'Хаях'),
(139, 'Distinct', 'Тодорхой'),
(140, 'Distort', 'Гажуудуулах'),
(141, 'Distribute', 'Түгээх'),
(142, 'Diverse', 'Олон янз'),
(143, 'Document', 'Баримт бичиг'),
(144, 'Domain', 'Хүрээ'),
(145, 'Domestic', 'Дотоодын'),
(146, 'Dominate', 'Ноёрхох'),
(147, 'Draft', 'Ноорог'),
(148, 'Drama', 'Драм'),
(149, 'Duration', 'Үргэлжлэх хугацаа'),
(150, 'Dynamic', 'Динамик'),
(151, 'Economy', 'Эдийн засаг'),
(152, 'Edit', 'Засварлах'),
(153, 'Element', 'Элемент'),
(154, 'Eliminate', 'Устгах'),
(155, 'Emerge', 'Гарч ирэх'),
(156, 'Emphasis', 'Онцлох'),
(157, 'Empirical', 'Туршлагын'),
(158, 'Enable', 'Боломжтой болгох'),
(159, 'Encounter', 'Тулгарах'),
(160, 'Enhance', 'Сайжруулах'),
(161, 'Enormous', 'Асар том'),
(162, 'Ensure', 'Баталгаажуулах'),
(163, 'Entity', 'Нэгж'),
(164, 'Environment', 'Орчин'),
(165, 'Equate', 'Тэнцүүлэх'),
(166, 'Equip', 'Тоноглох'),
(167, 'Equivalent', 'Адил тэнцүү'),
(168, 'Erode', 'Элэгдэх'),
(169, 'Error', 'Алдаа'),
(170, 'Establish', 'Байгуулах'),
(171, 'Estate', 'Үл хөдлөх'),
(172, 'Estimate', 'Тооцоолох'),
(173, 'Ethic', 'Ёс зүй'),
(174, 'Ethnic', 'Үндэстний'),
(175, 'Evaluate', 'Үнэлэх'),
(176, 'Eventual', 'Эцсийн'),
(177, 'Evident', 'Тодорхой'),
(178, 'Evolve', 'Хөгжих'),
(179, 'Exceed', 'Хэтрэх'),
(180, 'Exclude', 'Хасах'),
(181, 'Exhibit', 'Үзэсгэлэн'),
(182, 'Expand', 'Өргөжүүлэх'),
(183, 'Expert', 'Мэргэжилтэн'),
(184, 'Explicit', 'Тодорхой'),
(185, 'Exploit', 'Ашиглах'),
(186, 'Export', 'Экспорт'),
(187, 'Expose', 'Илчлэх'),
(188, 'External', 'Гаднын'),
(189, 'Extract', 'Гаргаж авах'),
(190, 'Facilitate', 'Хөнгөвчлөх'),
(191, 'Factor', 'Хүчин зүйл'),
(192, 'Feature', 'Онцлог'),
(193, 'Federal', 'Холбооны'),
(194, 'Fee', 'Хураамж'),
(195, 'File', 'Файл'),
(196, 'Final', 'Эцсийн'),
(197, 'Finance', 'Санхүү'),
(198, 'Finite', 'Хязгаарлагдмал'),
(199, 'Flexible', 'Уян хатан'),
(200, 'Fluctuate', 'Хэлбэлзэх'),
(201, 'Focus', 'Төвлөрөх'),
(202, 'Format', 'Формат'),
(203, 'Formula', 'Томьёо'),
(204, 'Forthcoming', 'Удахгүй'),
(205, 'Foundation', 'Суурь'),
(206, 'Framework', 'Хүрээ'),
(207, 'Function', 'Функц'),
(208, 'Fund', 'Сан'),
(209, 'Fundamental', 'Үндсэн'),
(210, 'Furthermore', 'Цаашлаад'),
(211, 'Gender', 'Хүйс'),
(212, 'Generate', 'Үүсгэх'),
(213, 'Generation', 'Үе'),
(214, 'Globe', 'Дэлхий'),
(215, 'Goal', 'Зорилго'),
(216, 'Grade', 'Дүн'),
(217, 'Grant', 'Тэтгэлэг'),
(218, 'Guarantee', 'Баталгаа'),
(219, 'Guideline', 'Удирдамж'),
(220, 'Hence', 'Тиймээс'),
(221, 'Hierarchy', 'Шатлал'),
(222, 'Highlight', 'Онцлох'),
(223, 'Hypothesis', 'Таамаглал'),
(224, 'Identical', 'Адилхан'),
(225, 'Identify', 'Тодорхойлох'),
(226, 'Ideology', 'Үзэл суртал'),
(227, 'Ignorance', 'Мэдлэггүй байдал'),
(228, 'Illustrate', 'Зурагдуулах'),
(229, 'Image', 'Зураг'),
(230, 'Immigrate', 'Цагаачлах'),
(231, 'Impact', 'Нөлөө'),
(232, 'Implement', 'Хэрэгжүүлэх'),
(233, 'Implicate', 'Холбогдуулах'),
(234, 'Implicit', 'Далд'),
(235, 'Imply', 'Илэрхийлэх'),
(236, 'Impose', 'Ногдуулах'),
(237, 'Incentive', 'Урамшуулал'),
(238, 'Incidence', 'Тохиолдол'),
(239, 'Incline', 'Хэлбийх'),
(240, 'Income', 'Орлого'),
(241, 'Incorporate', 'Нэгтгэх'),
(242, 'Index', 'Индекс'),
(243, 'Indicate', 'Заах'),
(244, 'Individual', 'Хувь хүн'),
(245, 'Induce', 'Өдөөх'),
(246, 'Inevitable', 'Зайлшгүй'),
(247, 'Infer', 'Дүгнэх'),
(248, 'Infrastructure', 'Дэд бүтэц'),
(249, 'Inherent', 'Төрөлхийн'),
(250, 'Inhibit', 'Саад болох'),
(251, 'Initial', 'Анхны'),
(252, 'Initiate', 'Эхлүүлэх'),
(253, 'Injure', 'Гэмтээх'),
(254, 'Innovate', 'Шинэчлэх'),
(255, 'Input', 'Оролт'),
(256, 'Insert', 'Оруулах'),
(257, 'Insight', 'Ойлголт'),
(258, 'Inspect', 'Шалгах'),
(259, 'Instance', 'Жишээ'),
(260, 'Institute', 'Хүрээлэн'),
(261, 'Instruct', 'Зааварлах'),
(262, 'Integral', 'Салшгүй'),
(263, 'Integrate', 'Нэгтгэх'),
(264, 'Integrity', 'Шударга байдал'),
(265, 'Intelligence', 'Оюун ухаан'),
(266, 'Intense', 'Эрчимтэй'),
(267, 'Interact', 'Харилцах'),
(268, 'Intermediate', 'Дунд'),
(269, 'Internal', 'Дотоод'),
(270, 'Interpret', 'Тайлбарлах'),
(271, 'Interval', 'Завсар'),
(272, 'Intervene', 'Оролцох'),
(273, 'Intrinsic', 'Дотоод'),
(274, 'Invest', 'Хөрөнгө оруулах'),
(275, 'Investigate', 'Судлах'),
(276, 'Invoke', 'Дуудах'),
(277, 'Involve', 'Оролцуулах'),
(278, 'Isolate', 'Тусгаарлах'),
(279, 'Issue', 'Асуудал'),
(280, 'Item', 'Зүйл'),
(281, 'Job', 'Ажил'),
(282, 'Journal', 'Сэтгүүл'),
(283, 'Justify', 'Зөвтгөх'),
(284, 'Label', 'Шошго'),
(285, 'Labor', 'Хөдөлмөр'),
(286, 'Layer', 'Давхарга'),
(287, 'Lecture', 'Лекц'),
(288, 'Legal', 'Хуулийн'),
(289, 'Legislate', 'Хууль тогтоох'),
(290, 'Levy', 'Татвар'),
(291, 'Liberal', 'Чөлөөт'),
(292, 'License', 'Лиценз'),
(293, 'Likewise', 'Мөн адил'),
(294, 'Link', 'Холбоос'),
(295, 'Locate', 'Байршуулах'),
(296, 'Logic', 'Логик'),
(297, 'Maintain', 'Хадгалах'),
(298, 'Major', 'Гол'),
(299, 'Manipulate', 'Удирдах'),
(300, 'Manual', 'Гарын авлага'),
(301, 'Margin', 'Зах'),
(302, 'Mature', 'Боловсорсон'),
(303, 'Maximize', 'Хамгийн их болгох'),
(304, 'Mechanism', 'Механизм'),
(305, 'Media', 'Хэвлэл мэдээлэл'),
(306, 'Mediate', 'Зуучлах'),
(307, 'Medical', 'Эмнэлгийн'),
(308, 'Medium', 'Дунд'),
(309, 'Mental', 'Оюуны'),
(310, 'Method', 'Арга'),
(311, 'Migrate', 'Нүүх'),
(312, 'Military', 'Цэргийн'),
(313, 'Minimal', 'Хамгийн бага'),
(314, 'Minimize', 'Багасгах'),
(315, 'Ministry', 'Яам'),
(316, 'Minor', 'Бага'),
(317, 'Mode', 'Горим'),
(318, 'Modify', 'Өөрчлөх'),
(319, 'Monitor', 'Хянах'),
(320, 'Motive', 'Шалтгаан'),
(321, 'Mutual', 'Харилцан'),
(322, 'Negate', 'Үгүйсгэх'),
(323, 'Network', 'Сүлжээ'),
(324, 'Neutral', 'Төвийг сахисан'),
(325, 'Nevertheless', 'Гэсэн хэдий ч');