// Streams a Bluebook explanation video from Google Drive through our edge function.
// The raw Drive URL never reaches the browser. Access is gated by an HMAC-signed,
// short-lived token generated by list-bluebook-videos.
//
// URL shape: /stream-bluebook-video?id=<driveFileId>&exp=<unixMs>&sig=<hex>

import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";

const GATEWAY = "https://connector-gateway.lovable.dev/google_drive/drive/v3";

const videoCorsHeaders = {
  ...corsHeaders,
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
  "Access-Control-Allow-Headers": [
    "authorization",
    "x-client-info",
    "apikey",
    "content-type",
    "range",
    "if-none-match",
    "if-modified-since",
  ].join(", "),
  "Access-Control-Expose-Headers": [
    "Accept-Ranges",
    "Content-Range",
    "Content-Length",
    "Content-Type",
    "ETag",
    "Last-Modified",
    "Cache-Control",
  ].join(", "),
};

function jsonResponse(body: unknown, status: number) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...videoCorsHeaders, "Content-Type": "application/json" },
  });
}


async function hmacHex(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let out = 0;
  for (let i = 0; i < a.length; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return out === 0;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: videoCorsHeaders });
  }

  if (req.method !== "GET" && req.method !== "HEAD") {
    return jsonResponse({ error: "method not allowed" }, 405);
  }

  try {
    const url = new URL(req.url);
    const id = url.searchParams.get("id");
    const exp = url.searchParams.get("exp");
    const sig = url.searchParams.get("sig");

    if (!id || !exp || !sig) {
      return jsonResponse({ error: "missing params" }, 400);
    }

    const expMs = Number(exp);
    if (!Number.isFinite(expMs) || Date.now() > expMs) {
      return jsonResponse({ error: "link expired" }, 401);
    }

    const signingSecret = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!signingSecret) throw new Error("signing secret unavailable");

    const expected = await hmacHex(signingSecret, `${id}.${exp}`);
    if (!timingSafeEqual(expected, sig)) {
      return jsonResponse({ error: "bad signature" }, 401);
    }

    // Drive's raw original files may be HEVC/H.265, which Chrome/Android often
    // reports as MEDIA_ERR_SRC_NOT_SUPPORTED. Proxy Drive's browser transcode
    // instead; it is still hidden behind this signed endpoint, but is H.264 MP4.
    const playableSource = await resolvePlayableSource(id);
    const lovableKey = Deno.env.get("LOVABLE_API_KEY");
    const driveKey = Deno.env.get("GOOGLE_DRIVE_API_KEY");

    const upstreamUrl = playableSource?.url
      ?? `${GATEWAY}/files/${encodeURIComponent(id)}?alt=media`;

    const upstreamHeaders: Record<string, string> = {
      "User-Agent": "Mozilla/5.0",
    };
    if (!playableSource) {
      if (!lovableKey || !driveKey) throw new Error("Drive connector not configured");
      upstreamHeaders.Authorization = `Bearer ${lovableKey}`;
      upstreamHeaders["X-Connection-Api-Key"] = driveKey;
    }

    // Forward the Range header so seeking / progressive playback works on mobile.
    const range = req.headers.get("Range");
    if (range) upstreamHeaders["Range"] = range;

    let upstream = await fetch(upstreamUrl, { method: req.method, headers: upstreamHeaders });

    if ((upstream.status === 403 || upstream.status === 404) && playableSource) {
      transcodeCache.delete(id);
      const freshSource = await resolvePlayableSource(id);
      if (freshSource?.url && freshSource.url !== playableSource.url) {
        upstream = await fetch(freshSource.url, { method: req.method, headers: upstreamHeaders });
      }
    }

    if (!upstream.ok && upstream.status !== 206) {
      const body = await upstream.text();
      console.error(`Drive stream failed [${upstream.status}]: ${body}`);
      return jsonResponse({ error: "upstream", status: upstream.status, details: body }, upstream.status);
    }

    // Pass through streaming headers so the browser can seek.
    const passHeaders = new Headers({ ...videoCorsHeaders });
    const forward = [
      "content-type",
      "content-length",
      "content-range",
      "accept-ranges",
      "last-modified",
      "etag",
    ];
    for (const h of forward) {
      const v = upstream.headers.get(h);
      if (v) passHeaders.set(h, v);
    }
    if (playableSource?.contentType) passHeaders.set("content-type", playableSource.contentType);
    if (!passHeaders.has("content-type")) passHeaders.set("content-type", "video/mp4");
    if (!passHeaders.has("accept-ranges")) passHeaders.set("accept-ranges", "bytes");

    // If the upstream honors a Range request but omits Accept-Ranges, keep the
    // exact upstream Content-Range/Length and only add the seekability marker.
    const contentRange = passHeaders.get("content-range");
    if (upstream.status === 206 && !contentRange) {
      console.warn("Range request returned 206 without Content-Range");
    }

    passHeaders.set("cache-control", "private, max-age=3600");
    // Force inline so the browser plays instead of downloading.
    passHeaders.set("content-disposition", "inline");

    return new Response(req.method === "HEAD" ? null : upstream.body, {
      status: upstream.status,
      headers: passHeaders,
    });
  } catch (err) {
    console.error("stream-bluebook-video error:", err);
    return jsonResponse({ error: err instanceof Error ? err.message : String(err) }, 500);
  }
});
