// Streams a Bluebook explanation video from Google Drive through our edge function.
// The raw Drive URL never reaches the browser. Access is gated by an HMAC-signed,
// short-lived token generated by list-bluebook-videos.
//
// URL shape: /stream-bluebook-video?id=<driveFileId>&exp=<unixMs>&sig=<hex>

import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";

const GATEWAY = "https://connector-gateway.lovable.dev/google_drive/drive/v3";

async function hmacHex(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let out = 0;
  for (let i = 0; i < a.length; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return out === 0;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const id = url.searchParams.get("id");
    const exp = url.searchParams.get("exp");
    const sig = url.searchParams.get("sig");

    if (!id || !exp || !sig) {
      return new Response(JSON.stringify({ error: "missing params" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const expMs = Number(exp);
    if (!Number.isFinite(expMs) || Date.now() > expMs) {
      return new Response(JSON.stringify({ error: "link expired" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const signingSecret = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!signingSecret) throw new Error("signing secret unavailable");

    const expected = await hmacHex(signingSecret, `${id}.${exp}`);
    if (!timingSafeEqual(expected, sig)) {
      return new Response(JSON.stringify({ error: "bad signature" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const lovableKey = Deno.env.get("LOVABLE_API_KEY");
    const driveKey = Deno.env.get("GOOGLE_DRIVE_API_KEY");
    if (!lovableKey || !driveKey) throw new Error("Drive connector not configured");

    // Forward the Range header so seeking / progressive playback works on mobile.
    const upstreamHeaders: Record<string, string> = {
      Authorization: `Bearer ${lovableKey}`,
      "X-Connection-Api-Key": driveKey,
    };
    const range = req.headers.get("Range");
    if (range) upstreamHeaders["Range"] = range;

    const upstream = await fetch(`${GATEWAY}/files/${encodeURIComponent(id)}?alt=media`, {
      method: "GET",
      headers: upstreamHeaders,
    });

    if (!upstream.ok && upstream.status !== 206) {
      const body = await upstream.text();
      console.error(`Drive stream failed [${upstream.status}]: ${body}`);
      return new Response(
        JSON.stringify({ error: "upstream", status: upstream.status, details: body }),
        { status: upstream.status, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // Pass through streaming headers so the browser can seek.
    const passHeaders = new Headers({ ...corsHeaders });
    const forward = ["content-type", "content-length", "content-range", "accept-ranges", "last-modified", "etag"];
    for (const h of forward) {
      const v = upstream.headers.get(h);
      if (v) passHeaders.set(h, v);
    }
    if (!passHeaders.has("content-type")) passHeaders.set("content-type", "video/mp4");
    if (!passHeaders.has("accept-ranges")) passHeaders.set("accept-ranges", "bytes");
    passHeaders.set("cache-control", "private, max-age=3600");
    // Force inline so the browser plays instead of downloading.
    passHeaders.set("content-disposition", "inline");

    return new Response(upstream.body, {
      status: upstream.status,
      headers: passHeaders,
    });
  } catch (err) {
    console.error("stream-bluebook-video error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : String(err) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
